### ISSUE TITLE
Maybe update links on main page for study groups?

### ISSUE THREAD

**Issue by sstevens2** [ComBEE-UW-Madison/studyGroup#14]
Python could go to https://combee-uw-madison.github.io/PythonStudyGroup/
and R to https://combee-uw-madison.github.io/RStudyGroup/ instead of the repo main page.  Though both are generated from the README I think this one looks a bit nicer.

The links within will still go to the repo though.  It might take more work to get all of the pages within the repos to be linked right but might be nice to have the main page like that.

Let me know what you two think. @kirstengott @elizabethmcd

**Comment by elizabethmcd** [comment]
My one issue with this is that then you can't see the repo folders. Sometimes in study groups we reference notes/code from previous semesters and this now seems like a round about way of getting there? I'm not sure. I definitely like the layout of these new links more, but I'll think on it some more. What do you think @kirstengott

**Comment by sstevens2** [comment]
Addressing @elizabethmcd's comment above, you could have a link to the repo on the README page so that during study group you can get there easily.  My main reasons for suggesting this is are I think people are a little more comfortable with the way the rendered website looks like and that in my experience GitHub can be intimidating for people who've never used it before.
If you(@elizabethmcd and @kirstengott) like the way it is better, feel free to disregard. 😄
